- pylxd/operation.py
- requirements.txt
Signed-off-by: Matthew Williams <mgwilliams@gmail.com>
Although the API spec says unix timestamps are returned by the API, in fact they are of the format `2015-06-09T21:05:29.00502626Z` (this is true in 0.9 through 0.11).
If it is desirable to avoid the dependency on python-dateutil, I can write a helper function using strptime. Or pylxd could just return the timestamp verbatim as returned by the API, since it's already human readable.
This PR also fixes a small typo that was causing a `404`.
> fix date parsing and typo

- CONTRIBUTING.rst
Get rid of the openstack boilerplate and indicate that we are accepting PRs
and issues on githhub.
Closes #1
Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>
> fix up CONTRIBUTING.rst

- pylxd/image.py
- pylxd/tests/test_image.py
LXD returns some data on upload; pass it back to callers.
> Switch to using get_object in image_upload

- .travis.yml
- setup.cfg
- test-requirements.txt
- tox.ini
os-testr provides a nice wrapper around testrepository as well
as support fast parallel execution.
> Use os-testr for test suite execution

- pylxd/operation.py
- pylxd/tests/test_operation.py
Instead of sometimes (in the case of list_operations) referring to
operations by their actual UUID and others (in the case of grabbing what
the API returns directly out of the response) referring to operations by
their full URL, let's just always use the full URL.
Closes #8
Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>
> refer to the operation by its URL always

- pylxd/container.py
- pylxd/tests/test_container.py
- setup.cfg
Instead of trying to get the state (which causes LXD to do a bunch of
forking/setnsing crap that is quite slow). Instead, let's just query the
list of the containers, which, in LXD is a DB query, and check if our
container is in that list.
Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>
> faster behavior for determining if a container is defined

- pylxd/container.py
Current code compares 'status' field in camel case with
with predefined statuses in upper case. That's why method
container_running() always returns False, even if container
is running.
> Fix issue in LXDContainer.container_running() method

- pylxd/connection.py
- pylxd/tests/test_connection.py
- requirements.txt
Ubuntu 14.04 doesnt have ssl.PROTOCOL_TLSv1_2, so check  to see if we have ssl.PROTOCOL_TLSv1_2 available otherwise use OpenSSL.SSL.TLSv1_2_METHOD.
Fixes issue #42
> Detect SSL TLS version

- pylxd/connection.py
- pylxd/container.py
- pylxd/operation.py
- pylxd/tests/test_connection.py
- requirements.txt
This commit adds websockets support in PyLXD library which allows
users track progress and output of executed operations and commands.
This commit is required to use PyLXD in Openstack Manila project.
This pull request closes issue #26
> Remove get_ws() method stub with real websocket implementation

- pylxd/connection.py
Since 0.24 LXD doesn't terminate web socket and it should be closed by client via close() method.
> Remove override of close() in WebSocketClient

- .travis.yml
- blacklist
- examples/api_test.py
- integration/test_base.py
- pylxd/api.py
- pylxd/tests/test_api.py
- requirements.txt
- setup.py
- test-requirements.txt
- tox.ini
This is the start of a re-work of the LXD api client for python.
The next step, after this, is to go through the LXD spec itself and implement the client per the spec, thus making sure the client is spec'd properly, but also forcing LXD to have implemented the spec properly.
This code isn't currently being used yet. Once the full client is implemented, we'll deprecate the old code (which, we've recently learned, doesn't work at all on python3).
> The end is near

- pylxd/deprecated/connection.py
- pylxd/deprecated/tests/test_connection.py
This otherwise fail to build in Jessie, and I'm adding this patch to the Debian package.
> Fix six.PY34 into six.PY3

- pylxd/client.py
- pylxd/container.py
- pylxd/containerState.py
- pylxd/image.py
- pylxd/operation.py
- pylxd/profile.py
I needed those two changes to get lxc-to-lxd working with the non-deprecated pylxd API.
I'm reasonably sure the the quote commit is properly backward compatible, I'm not so sure about the iteritems() one though, if it's not, we'll need a wrapper function which takes a dict and calls the right thing depending on python version.
> Python3 fixes

- .coveragerc
- pylxd/client.py
- pylxd/deprecated/connection.py
- pylxd/tests/mock_lxd.py
- pylxd/tests/test_client.py
- pylxd/tests/test_container.py
- pylxd/tests/test_image.py
- pylxd/tests/test_profile.py
- pylxd/tests/testing.py
- test-requirements.txt
As we've seen significant uptick in the use of pylxd recently, and some demand for good testing, this patch adds unit tests for the newer API. It adds a mock service for requests, so the entire test suite can be run without a LXD instance at all. Currently, it puts the unit test coverage at 70% of the new API. While writing these tests, I also found a bug in the `LXD_DIR` logic of the client, and fixed that (something initial tests would have caught...)
This infrastructure is a start, and should make it easier for others to contribute without having to make up some random mock service system. It's definitely not the end of what it should be (and there's even an `XXX` comment to that effect in this patch).
While running these tests on various platforms (to make sure they run fine outside …
> Mock LXD services

- pylxd/__init__.py
- pylxd/client.py
- pylxd/exceptions.py
- pylxd/tests/mock_lxd.py
- pylxd/tests/test_client.py
The client init will raise an exception if the endpoint isn't accessible. This fixes one of the two issues I've discovered while trying to sort out what's going on with my local lxd install.
> Verify client connection

- pylxd/profile.py
- pylxd/tests/test_profile.py
Currently it not possible to specify devices when creating a
LXD profile. Make config and devices
optional when creating an LXD profile. This is required
so we can attach disks, network interfaces, etc.
> Allow specification of devices in a profile

- pylxd/container.py
- pylxd/exceptions.py
- pylxd/image.py
- pylxd/profile.py
- pylxd/tests/mock_lxd.py
- pylxd/tests/test_container.py
- pylxd/tests/test_image.py
- pylxd/tests/test_profile.py
- pylxd/tests/testing.py
We've always known that our error handling has needed work. The original API over-caught things, and the new API doesn't catch anything. The new api's inability to catch things results in some really random errors (like, when `wait=True`, not finding the `operation` key in the returned dict).
We will likely need some sort of assertion on _every_ request we make, that makes sure we have the proper return statuses. We'll also need to think about the extra information we include in these new exceptions (a core reason why I try and use built-ins when I can).
> Add more exceptions to the API

- integration/test_containers.py
- integration/testing.py
Fixes:
{u'type': u'error', u'error_code': 400, u'error': u'json: cannot unmarshal number into Go value of type string'}
> Make architecture a string type

- pylxd/container.py
- pylxd/exceptions.py
- pylxd/image.py
- pylxd/profile.py
- pylxd/tests/mock_lxd.py
- pylxd/tests/test_container.py
- pylxd/tests/test_image.py
- pylxd/tests/test_profile.py
We currently have a bug where, if an object is fetched via `all`, it's not yet a complete object. We only have the single identifying property. It must first be populated before we can really interact with it. `Container` already had some support for this, but if one tried to call `update` on a partial object before fetching, it would result in a less than friendly `AttributeError` when trying to marshall the object. `Profile` and `Image` had to grow support for `fetch`, while `Container`'s api needed to be renamed (with the old name kept around for backwards compatibility.
> Partial objects and updating

- pylxd/client.py
- pylxd/container.py
- pylxd/managers.py
The best thing about a good API is that it's guessable, and that the process of extending it has a clear path. The manager methods we provided were nice, but it quickly became clear in #115 that we needed a better/quicker/cleaner way of adding a manager. This simplifies the process greatly.
> Refactor the manager protocol to be a little cleaner

- pylxd/tests/mock_lxd.py
- pylxd/tests/test_container.py
- pylxd/tests/test_profile.py
I was writing some tests and discovered that, well, our mock service was allowing a little too much through. This should make it stricter by removing some wildcard regexes.
> Update the mock service to be more strict

- .coveragerc
I added a commit hook that removed some cache files, like the coverage cache, and suddenly, I found a bunch of coverage stuff I had been missing. This patch adds some exclusions, like ignoring `__str__` methods. Also, apparently if you specify `exclude_lines`, you have to add the default `pragma: no cover` to it.
> Add coverage exclusions

- pylxd/container.py
- pylxd/exceptions.py
- pylxd/tests/mock_lxd.py
- pylxd/tests/test_container.py
This branch adds a manager-esque `FilesManager` to handle files, with accompanying tests.
Please review #120 first (I merged that into this branch; writing these tests were how I realized how loose the mock service was)
> Files manager

- pylxd/client.py
- pylxd/tests/mock_lxd.py
- pylxd/tests/test_client.py
Cache LXD host info so that it can be queried via the API.
> Cache LXD host info

- integration/test_containers.py
- integration/test_images.py
- integration/test_profiles.py
- integration/testing.py
- pylxd/container.py
- pylxd/profile.py
- pylxd/tests/mock_lxd.py
This branch fixes the integration tests. There are a few things to address here:
- The tests have no external dependencies, and require no outside setup.
- The tests clean up after themselves (using `addCleanup`, with the exception of when something goes very wrong; this seems more a bug in `unittest` than our issue)
- The integration tests take 20 seconds on my machine (addressing somewhat unfounded concerns about them taking "too long")
- The integration tests uncovered two bugs: (1) The deprecated `Container.delete_snapshot` wasn't forwarding the `wait` parameter, and (2) `Profile.create` returns a 200, not a 202 (because it's a synchronous operation).
After this is merged, I'll connect with Stephane and get them connected to the lxd jenkins.
> Fix integration tests

- integration/test_containers.py
- integration/test_images.py
- integration/testing.py
- pylxd/client.py
- pylxd/container.py
- pylxd/exceptions.py
- pylxd/image.py
- pylxd/profile.py
- pylxd/tests/mock_lxd.py
- pylxd/tests/test_client.py
- pylxd/tests/test_container.py
- pylxd/tests/test_image.py
- pylxd/tests/test_profile.py
This is a first pass at unifying the error handling of pylxd. The LXD API response codification is pretty tight, and it's pretty easy to figure out when something isn't right. I think there are probably a few more patches that can happen to help organize this a bit, but this is a good start.
Most of the patch is updating the tests to act more like the LXD API.
> Better http assertions

- pylxd/container.py
- pylxd/tests/mock_lxd.py
- pylxd/tests/test_container.py
While exploring the container state issue (that ended up being a non-issue), I added a bunch of test coverage...kinda. I mean, it executes the code path, but makes no assertions, which makes me slightly uncomfortable, but after pouring through the mock_services docs, it seemed non-trivial to handle that, and probably needs some re-working beyond the scope of a small branch.
> Add more tests for container state

- doc/source/usage.rst
- pylxd/client.py
- pylxd/tests/test_client.py
Add support for the events websocket.
This was a little...special...in that we've mostly had this consistent API for working with a HTTP stateless api, and now we have what is essentially a socket client. I tried to document this as clearly as possible, but it's entirely possible that we'll have to iterate on this API a few times before it "feels right".
> Events websocket

- integration/test_containers.py
- pylxd/client.py
- pylxd/container.py
- pylxd/tests/mock_lxd.py
- pylxd/tests/test_container.py
This patch changes the semantics of `Container.execute` a bit. Now it can _only_ take a list as a command argument (this is required as a lxd implementation detail). It also returns the stdout and stderr as text from the command (i.e. it now blocks waiting for the command to be run). This required some...adventurous...websocket work. If anything doesn't seem clear, just let me know and I'll try and add some documentation.
> Execute interactive

- pylxd/container.py
- pylxd/image.py
- pylxd/mixin.py
- pylxd/operation.py
- pylxd/tests/test_operation.py
Simplify the `Operation` handling work.
In general, operational work is entirely an implementation detail that we want to hide from the user. However, I made these two changes because it just made it easier for me as a developer (and reduced some repeated code).
> Operation work

- integration/test_containers.py
- requirements.txt
This branch does a two things:
- It fixes the integration tests to not raise `DeprecationWarning`s by using the current APIs.
- It prevents the upgrade to ws4py `0.3.5` which breaks unix sockets. I'm not sure whether we should chase this. The maintainer of ws4py doesn't seem interested in maintaining it
> Integration cleanup

- pylxd/certificate.py
I thought I had handled this properly, but I guess not. When trying with a new host, I needed to add this code back in. It basically strips out the `-----BEGIN CERTIFICATE-----` and `-----END CERTIFICATE-----` lines of the cert.
I wonder if LXD should accept this standard PEM format rather than just blowing up.
> Fix the cert handling.

- pylxd/client.py
- pylxd/managers.py
- pylxd/model.py
- pylxd/network.py
- pylxd/tests/mock_lxd.py
- pylxd/tests/test_model.py
- pylxd/tests/test_network.py
- test-requirements.txt
- tox.ini
We've talked a few times about how LXD object representations would be able to keep track of their state. For instance, has the instance been modified since it was retrieved from the server? If not, there's no reason to call `update`.
I also tried to use this time to sort out the object lifecycle as well. There's the creation (done via `get` \ `create`), what is currently referred to as `fetch` but is being reconsidered as `sync` (obviously, with a `DeprecationWarning` when implemented in the other objects) to sync up a partial object gotten via `all`, `update` (being renamed to `save`) for putting changes back into the server, and `delete` for...deleting.
I wanted to take this experiment into the realm of practical, so I implemented `/1.0/networks`, which was the last endpoint that …
> Stateful object experiment

- pylxd/certificate.py
- pylxd/client.py
- pylxd/container.py
- pylxd/image.py
- pylxd/model.py
- pylxd/network.py
- pylxd/operation.py
- pylxd/profile.py
- pylxd/tests/mock_lxd.py
- pylxd/tests/test_certificate.py
- pylxd/tests/test_client.py
- pylxd/tests/test_container.py
- pylxd/tests/test_image.py
- pylxd/tests/test_profile.py
`Container`, `Snapshot`, `Image`, `Profile`, and `Certificate` have all been updated to the stateful `Model` API that was merged this weekend.
> Update all objects to the model API

- pylxd/model.py
- pylxd/tests/test_model.py
This patch adds the ability for the model to know what changed since the last sync. This would allow us to do things like use PATCH instead of PUT. It also added some transactional elements, like the ability to rollback all your local changes to whatever is on the server.
I also found a bug in the marshalling around `Attribute.readonly`. That is now fixed.
> Attribute state

- pylxd/client.py
- pylxd/tests/test_client.py
Allow to specify an existing socket as endpoint and quote it for requests.unixsocket.
> Quote the path of unix endpoints.

- pylxd/container.py
- pylxd/tests/mock_lxd.py
Fix traceback when using pylxd with 2.1:
File "/opt/stack/pylxd/pylxd/model.py", line 105, in __init__
setattr(self, key, val)
File "/opt/stack/pylxd/pylxd/model.py", line 126, in __setattr__
return super(Model, self).__setattr__(name, value)
AttributeError: 'Container' object has no attribute 'last_used_at'
> Fix traceback when using when LXD 2.1

- pylxd/model.py
- pylxd/tests/test_model.py
LXD adding new properties shouldn't cause current applications to fail,
but it is appropriate for pylxd to emit warnings about them.
> Warn but don't raise exception on unknown attributes.

- integration/test_containers.py
- integration/test_images.py
- integration/test_profiles.py
- pylxd/models/_model.py
- pylxd/models/container.py
(We're still leaving in `pylxd.deprecated`)
> Remove the deprecated apis in preparation for pylxd 2.1

- run_integration_tests
The integration tests require a pretty clean environment, so running
them in my dev environment gets...weird sometimes. This will fire up
a container and run it inside that container. The caveat is that the
container is still (currently) privileged, so don't just run anyone's
integration tests on your machine. Look at them first.
> Add script to easily run the integration tests.

- pylxd/client.py
- pylxd/models/container.py
- pylxd/tests/models/test_container.py
If a connection to LXD is a local connection, it should not be used to migrate, because it won't have a routable connection.
Originally, I had the idea that we could iterate through all the addresses in `metadata.environment.addresses` until we found a valid one, and while that made me laugh at the stupidity and possible genius of the hack, I think it's better to explicitly put the burden on the user to have a routable connection.
> Don't allow local connection clients to migrate

- pylxd/client.py
- pylxd/deprecated/connection.py
- pylxd/models/container.py
- pylxd/tests/models/test_container.py
- pylxd/tests/test_client.py
- pylxd/tests/testing.py
Tests that require ws4py are skipped in environments that don't have
ws4py available.
Fixes #180
> Make ws4py an optional library.

- doc/source/images.rst
- integration/test_containers.py
- integration/test_images.py
- pylxd/client.py
- pylxd/models/image.py
- pylxd/tests/mock_lxd.py
- pylxd/tests/models/test_image.py
- run_integration_tests
This branch adds the integration test for `Container.publish` and fixes the issue with `Image.export` storing the contents of the image in memory.
I updated the docs for `Image.export`, and fixed a small issue in `run_integration_tests` (which has become invaluable).
Sorry for the erroneous docstring changes. My editor does that automatically.
> Image export

- pylxd/models/network.py
Add "config" and "managed" attributes to the Network model. In addition
to be generally useful information, it also fixes warnings we were
getting upon calling `Client.networks.get()` about these attributes not
existing.
> Add missing attributes to Network model

- doc/source/containers.rst
I understand that the config specification for `create()` is beyond the
scope of the documentation, but I had to look directly in lxd's code to
figure how to create a container from a local image, something which, I
think, is a rather common usage of (py)lxd.
In this commit, I add an example of such config.
This additional example should be benefical to many other users.
> Improve documentation with a new container example

- pylxd/models/container.py
This branch does a number of things. First, it simplifies _StdinWebsocket,
as we don't need most of what existed there. It closes immediately
after connection (and the command doesn't execute unless stdin is
also connected).
_CommandWebsocketClient learned how to pre-emptively close a connection.
We were previously waiting for the command to time out, which is why
the execute call was taking so long. This fixes #182.
The while loop that waits for the commands to complete had too long of
a delay, and had too much logic for whether the loop should continue
to wait. That while loop was also simplified.
> Fix the ws4py connection handling for container execution

- pylxd/__init__.py
- pylxd/deprecated/tests/__init__.py
At this point, we should deprecate the code so far as to see that
anywhere it's being used has "pylxd.deprecated" in the import. I
think this makes sense for nova-lxd, but also for any code still
using the old API.
> Fully deprecate the old api

- pylxd/models/container.py
- pylxd/tests/mock_lxd.py
- requirements.txt
Container.execute needs a sane, safe way to return more properties
than just stdout/stderr. Container.execute_with_result will return
a ContainerExecuteResult with the exit code, stdout and stdin, and
provides a mechanism for returning more properties in the future.
Container.execute now raises a DeprecationWarning as its return
value will change in 2.2
> Add Container.execute_with_result

- requirements.txt
pyOpenSSL is a requirement for TLS 1.2 support in Python versions prior
to 2.7.9.
> Require pyOpenSSL for older Python releases

- integration/test_client.py
- pylxd/client.py
- pylxd/tests/test_client.py
- run_integration_tests
A number of bugs all conspired to make sure authentication didn't work (and I'm not sure how it ever worked...) This branch fixes them all and adds an integration test to make sure it doesn't break again.
- `pylxd.Client` had no `cert` attribute, which broke `authenticate`
- If the endpoint url specified in `pylxd.Client` creation ended in a trailing slash, LXD was responding with 301 redirects (appropriately) which also broke authentication
- The integration tests needed to be modified to support listening on the public http interface to test the authentication mechanism.
> Authenticate fixes

- pylxd/models/image.py
- pylxd/tests/models/test_image.py
In some cases, a user may want to upload a manifest with a raw image,
and pylxd previously didn't support that. This patch adds the needed
functionality.
As I did this, I found a bug in Image.create where fingerprint isn't
always reliably determined, so I have deprecated the ability to pass
a wait parameter to Image.create.
Fixes issue #172
> Allow multipart form uploads for images.

- requirements.txt
A request came in to audit pylxd requirements to line up better
with Openstack. There isn't much overhead to maintaining it with
cryptography, as those developers are pretty responsible.
> Support more cryptography versions.

- pylxd/client.py
- pylxd/exceptions.py
- pylxd/models/_model.py
- pylxd/models/container.py
- pylxd/models/image.py
- pylxd/models/profile.py
- pylxd/tests/models/test_container.py
- pylxd/tests/models/test_image.py
- pylxd/tests/models/test_profile.py
- setup.cfg
A common API issue that users report is an easier way to detect when an object just doesn't exist. This is becoming more and more apparent as I update methods in nova-lxd.
Add `NotFound` in the case of 404, which inherits from `LXDAPIException`, so it doesn't break backwards compatibility.
`Container`, `Image`, and `Profile` now have a `exists` class method, so that one can do `client.containers.exists('an-container')` as a wrapper around this new functionality.
> Add `NotFound` and `exists`

- pylxd/managers.py
- pylxd/models/container.py
I've been receiving the too many open files issue pointed out in Issue #209 using lxd to run containers in a testing environment. 
This is a simple patch that prevents exhausting file descriptors after "too many" calls to execute. Not sure if this is the greatest approach but it's a simple fix.
> Add websocket context manager

- pylxd/models/container.py
Don't sync() when stopping an ephermal container since that throws a NotFound exception.
> Fix ephermal container stop

- pylxd/models/container.py
This is to fix a bug I was regularly seeing when pulling attributes of a container:
`AttributeError: 'Container' object has no attribute 'description'`
> Added description to container.

- .travis.yml
- pylxd/tests/mock_lxd.py
- setup.cfg
- test-requirements.txt
The whole test suite was broken lately for three reasons:
1. Version in `setp.cfg` was out of sync with git tagging, making `pbr`
scream.
2. `mock_services` is outdated and unmaintained and doesn't work with
newer versions of `requests-mock`.
3. The newly added `description` property wasn't properly added in
mocked LXD.
I've fixed those two problems by updating the `setup.cfg` version,
pinning `requests-mock` to the last version to work and adding a
`description` field to the mocks.
On my machine, all tox tests pass now.
> Fix broken CI testing

- .travis.yml
- pylxd/models/_model.py
- pylxd/tests/mock_lxd.py
- setup.cfg
- test-requirements.txt
It's been a few times now (ref #188, #230) where we're in a tricky situation because a new attribute in LXD makes pylxd crash. It's not fun because it makes us *have* to update pylxd and LXD at the same time.
This commit makes models ignore `AttributeError` during `sync()`, which should normally fix this problem once and for all.
Depends on #233
> Make models resilient to new attributes in LXD

- pylxd/client.py
- pylxd/tests/test_client.py
Added request timeout kwarg for Client -> _APINode instance + possibility to set custom timeout for each get/post/put/delete
problem: for now pylxd have no request timeout, so on busy servers or if firewall drops request - pylxd client may hang forever
fix: pass timeout kwarg when initializing client object to set global timeout for requests. By default timeout set to None (backwards compatibility)
usage:
* set client timeout (connect, read) for all requests:
`cli = pylxd.Client(endpoint=..., ..., timeout=1)`
* set client connect timeout to 1s and client read timeout to 2s for all requests:
`cli = pylxd.Client(endpoint=..., ..., timeout=(1, 2))`
* redefine client timeout for current request to 1000s:
```
cli = pylxd.Client(endpoint=..., ..., timeout=1)
cli.api.get(timeout=1000)
```
> timeout kwarg for client object

- pylxd/client.py
When using a snap installed LXD, we need to look in the $HOME/snap
directory rather than looking in ~ for the certificates
Fixes #251
> Update cert check to look in snap path as well

- pylxd/models/image.py
- pylxd/tests/models/test_image.py
- requirements.txt
Existing version load image into memory when non-unified image used
(with separate tarball with manifest).
Added ability for stream based image upload without loading them to memory.
requests-toolbelt external package required for streaming multipart HTTP
image upload.
> Image import - memory hog fix

- README.rst
This is to allow the toplink on github to become the API link
rather than a link to the containers page.
Fixes #224
> Add some doc links to the README.rst

- .gitignore
- doc/source/api.rst
- doc/source/conf.py
- doc/source/containers.rst
- doc/source/images.rst
- doc/source/index.rst
- doc/source/networks.rst
- doc/source/operations.rst
- doc/source/profiles.rst
- doc/source/storage-pools.rst
- doc/source/usage.rst
Update the documentation to match the current functionality offered by the library.
Fixes to docs to remove warnings/errors from sphinx autodoc class documentation generation.
Additions of several pages to cover new functionality.
Closes #260 
Closes #263
> Update the containers documentation for 2.2.5

- .travis.yml
- pylxd/model.py
- pylxd/tests/mock_lxd.py
- requirements.txt
- setup.cfg
- test-requirements.txt
Bug #232 ('Container' object has no attribute 'description') breaks v2.0.5 packaged in Ubuntu Xenial 16.04 LTS as a backport to lxd 2.0.11 grew a new attribute called 'description' on the container JSON returned from lxd.  This breaks v2.0.5.  v.2.24 of pylxd grew the ability to ignore attributes it didn't know about and thus work with lxd 2.0.11.
> Fix bug #232 for 2.0 series branch

- pylxd/models/container.py
- pylxd/tests/models/test_container.py
Fix up the file mode str-ing to work with Python 3.
Add tests to check that headers are being set according to policy.
Add docstring to the `put` method to describe how to use the feature.
Original work by @keesbos.
> Add mode/uid/gid to the container put method

- pylxd/models/operation.py
- pylxd/tests/models/test_operation.py
lxd 3.0.0-beta{x} grew a new feature in that the operation metadata
includes a 'description' tag.  This breaks pylxd, and so this fix adds
the 'description' key, and also then makes the class more robust to
handle unknown attributes in the future.  Note that ALL the other
classes got this fix in 2.2.4.
Fixes bug: #284
> Fix Operation class to allow unknown attributes

- pylxd/operation.py
- pylxd/tests/test_operation.py
- setup.cfg
Fix Operation class to allow unknown attributes (cherry pick)
lxd 3.0.0-beta{x} grew a new feature in that the operation metadata
includes a 'description' tag.  This breaks pylxd, and so this fix adds
the 'description' key, and also then makes the class more robust to
handle unknown attributes in the future.  Note that ALL the other
classes got this fix in 2.2.4.
> Branch 2.0

- integration/test_containers.py
- integration/test_images.py
- integration/test_profiles.py
- run_integration_tests
- setup.cfg
The integration tests in the integrations/ sub-folder has bit-rotted.
This patch brings them up to date so that they work with the branch-2.0
current.  This is for SRU testing for xenial, which the branch-2.0
tracks releases for.
> Fix branch-2.0 integration tests

- integration/test_profiles.py
- setup.cfg
Add back in the skipped profile rename test on the integration test suite and bump the version to make pbr happy when running those tests.
> Add back profile rename integration test

- integration/test_profiles.py
- pylxd/client.py
- pylxd/models/container.py
- pylxd/tests/mock_lxd.py
- pylxd/tests/models/test_container.py
The issue was that the files handling uses the API get code path to
fetch files.  Thus json files were intepreted as an API reponse and
checked for content.  This change ensures that the contents of files are
returned without trying to interpret the contents.
> Fix bug/281 unable to get file with json content

- integration/test_containers.py
- pylxd/models/container.py
This patch adds support to control the decoding of the stdout
and stderr when executing commands in a container.  It is possible to
force a particular decode, or just get the raw buffers.  The existing
behaviour of trying to decode to utf-8 is retained if no decode or
encoding paramters are passed to the execute method.
Tests are in the integration/test_containers.py file as it's tricky to
test properly in a unit test.
> Enable decoding control over stdout/stderr on execute

- CONTRIBUTORS.rst
- doc/source/networks.rst
- integration/test_networks.py
- integration/testing.py
- pylxd/exceptions.py
- pylxd/models/_model.py
- pylxd/models/network.py
- pylxd/tests/mock_lxd.py
- pylxd/tests/models/test_network.py
I added support for operations on networks. I based my code on Profile model because it was quite similar. However, due to issue #302 it's not possible to test my changes using 'run_integration_tests' script on Ubuntu 16.04 and after switching to 17.10 my tests are passing but few other are failing (due to missing storage pool).
> Add network operations

- setup.py
Fixes #308 
```
New python executable in /home/pdecat/workspaces/thirdparty/pylxd/test/bin/python                                                                                                                              
Installing setuptools, pip, wheel...done.                                                                                                                                                                      
Installed /home/pdecat/workspaces/thirdparty/pylxd/.eggs/requests_unixsocket-0.1.5-py2.7.egg                                                                                                                   
Searching for requests!=2.8.0,>=2.5.2 …
```
> Put runtime dependencies in install_requires (fixes #308)

- setup.py
Follow up on #309 to fix #308 but keep build time dependency `pbr` in `setup_requires` and remove the following warning:
```
./.venv/bin/python setup.py --help                                                            
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'pbr'                                                                                                                      
warnings.warn(msg)                                                                                                                                                                                           
Common commands: (see '--help-commands' for more) …
```
> Keep pbr dependency in setup_requires (fixes #308, follows #309)

- doc/source/containers.rst
- pylxd/models/container.py
I have added the example on how to migrate a container using pylxd 
As agreed in #315
The migration fails due to an error but the example should be correct
> Added example on how to use the migrate API

- integration/test_containers.py
- pylxd/models/container.py
Fix issue #316 and issue #244 
It works (tox and integration tests) with lxd versions 3.0.1 and 2.0.11
Can be tested with this script to view some new features:
```python
from pylxd import Client
import io
import logging
logger = logging.getLogger(__name__)
handler = logging.StreamHandler()
handler.setFormatter(
logging.Formatter("%(relativeCreated)6d %(threadName)s %(message)s")
)
logger.addHandler(handler)
logger.setLevel(logging.INFO)
c = Client()
cont = c.containers.all()[0]
if cont.status != "Running":
cont.start(wait=True)
logger.info(cont.execute(["cat", "-"], stdin_payload=open(__file__)).stdout)
logger.info(cont.execute(["cat", "-"], stdin_payload="hola"))
logger.info(cont.execute(["cat", "-"], stdin_payload=b"hola"))
logger.info(cont.execute(["cat", "-"], …
```
> Fix execution times in lxd 3.0.1 and add pipelining support to execute

- integration/run_integration_tests
- integration/run_integration_tests-16-04
- integration/run_integration_tests-18-04
- run_integration_tests
Move the scripts to the integration/ directory, and enable the
`run_integration_tests` script to choose the Ubuntu version specific
script based on the output of lsb_release.
> Tidy up integration script tests

- pylxd/tests/models/test_container.py
- setup.cfg
- tox.ini
PEP8 keeps adding new default warnings, so we have to either fix
the code of config them out.  In this case, a bit of both.
> Bump version to 2.2.9 for dev and fix some pep8 issues

- pylxd/models/container.py
Signed-off-by: lasizoillo <lasizoillo@gmail.com>
LXD sends TextMessage frames until the last one, then send a BinaryMessage and closes connection. If connection is closed no read events can't arrive to EPollPoller and ws4py doesn't read more data. But ws4py get into a loop in some cases waiting for streaming data to complete a message frame. There are another infinite loop waiting to ws4py to drain connection buffer.
I hope this fix resolve all corner cases. If not, I hope be more free to fix it sooner.
> Fix race condition in 2.2.8 generating long pauses

- integration/test_containers.py
- pylxd/client.py
The migration tests merged as part of the migration code (commit
ad07da988082249dfbffc27f02b422a93c19e765) are basically broken; the
actual code is fine / this commit removes those tests (skips) so that CI
can continue.
The second part is improving the cert discovery for the client which is
broken if 'lxd.migrate' is issued on a bionic machine.  This tightens
the discovery.
> Remove broken migration tests and fix cert discovery

- requirements.txt
- setup.py
This is due to a medium security alert: CVE-2018-18074.
https://nvd.nist.gov/vuln/detail/CVE-2018-18074
> Update requests to minimum version 2.20.0

- pylxd/models/container.py
- pylxd/models/operation.py
- pylxd/tests/mock_lxd.py
- pylxd/tests/models/test_operation.py
the LXD Rest api returns an operation id with the query string
`?project=default` to notify in which project the operation belongs. This
was not sufficiently cut away by `.split('/')[-1]`
but also needed a subsequent `.split('?')[0]`
The Mock_lxd has been adapted to test for this feature
In the `container.execute` the `operation_id` is needed directly, where it
is fixed too
Signed-off-by: Felix Engelmann <fe-github@nlogn.org>
> Added compatibility with operations project values

- doc/source/containers.rst
- pylxd/models/container.py
- pylxd/tests/models/test_container.py
It might be interesting to get the websockets to interact with a container, e.g. on a shell.
Therefore interactive_execute on a container returns a data and control websocket. By design of lxd, they include a secret, so no additional authentication is required to connect to them. They are then perfect to be passed to a web terminal.
> Interactive Execute on Container

- pylxd/models/container.py
Update the pydoc for container's execute method to clarify the return
value.
Signed-off-by: Adam Israel <adam@adamisrael.com>
> Update pydoc for container.execute

- doc/source/containers.rst
- pylxd/models/container.py
- pylxd/tests/mock_lxd.py
- pylxd/tests/models/test_container.py
This patchset adds restore methods to the Container and Snapshot classes
to make it possible to restore a snapshot without having to use the
raw_api in pylxd.
Closes: #353
> Add restore snapshot methods

- doc/source/containers.rst
- pylxd/models/container.py
- pylxd/tests/models/test_container.py
The LXD api provides a parameter to kick of live migrations.  See
https://github.com/lxc/lxd/blob/master/doc/rest-api.md#post-optional-targetmember-1
for further details.
Closes: #338
> Add live parameter for migrations

- pylxd/client.py
When constructing the call, the [next-part] method creates the next
element in the chain of /part/<nextpart>.  However, it doesn't pass
through the timeout parameter which means that it doesn't end up on the
final call.  This patch fixes that.
> Fix dropped timeout in pylxd/client.py

- doc/source/usage.rst
- pylxd/models/_model.py
- pylxd/models/operation.py
- pylxd/tests/models/test_model.py
- pylxd/tests/models/test_operation.py
- tox.ini
If the LXD server that pylxd is connected to supports attributes on
objects that pylxd doesn't yet support, then a warning is issued using
the `warnings` module.  This can fill logs with annoying warnings.  So
this patch adds the ability to set an env variable PYLXD_WARNINGS to
'none' to suppress all the warnings, or to 'always' to get the existing
behaviour.  The new behavior is to issue a warning once for each
instance of an attribute that isn't known for each object.
Closes: #301
> Add PYLXD_WARNINGS env variable to be able to supress warnings

- pylxd/models/container.py
For the container execute command, if the command executed has pauses in
the output text, the websocket will send binary messages.  These were
interpreted as the stream being completed, and pylxd closed the
websocket, thus losing the rest of the output.
Delving into the code indicated some very strange behaviour across the
threads, so as part of solving the problem, this has been cleaned up as
well.
Closes: #362
> Fix execute command missing output with pauses in output text

- pylxd/models/container.py
Essentially, the behavior changed for when a caller to the
container's execute method wished to handle the packets received back on
the websocket.  This change fixes the reversion.
> Fix change of behaviour on execute introduced in #363

- pylxd/client.py
- pylxd/tests/test_client.py
A previous change (which added LXD_DIR) switched around the detection of
whether LXD is installed as a snap or a package to "test for packaged
first".  Unfortunately, the LXD pkg leaves behind the unix socket after
it is uninstalled when the snap is installed on xenial and a lxd.migrate
command is issued.  This means that the detection code fails.  This
patch reverts the behaviour to look "test for snapped first".
This is reasonable as the only way that a both unix socket files could
exist is if the snapped version was added to a pkg version default
install (e.g. Xenial).  As running both isn't really a supported
scenario, the default of checking for the snap first is more likely to
work in most default scenarios.  The LXD_DIR environment variable is
still available if it needs overriding …
> Switch around detection of whether unix socket is snap or pkg

- doc/source/profiles.rst
It was discovered that using profile.config and profile.devices as left-hand-sides to a .update function was setting them to "none" and the profile.update() was not actually saving.  profile.save() was also causing the profile settings to be blanked out due to the NoneTypes being set to profile.config and profile.devices.  Also expanded profile attribute descriptions to explicitly note types
> Updated example of profile updating and saving

- pylxd/client.py
- pylxd/tests/test_client.py
The LXD resources endpoint returns hardware information about LXD host. This
data is retrieved only when called. The data is cached as it won't change.
Signed-off-by: Lee Trager <lee.trager@canonical.com>
> Add support for the resources endpoint.

- pylxd/models/instance.py
It appears that the manager.close_all() can cause a broken pipe
error.  At this stage, that means that the pipe is closed and thus
it's actually okay to just continue and ignore the error (as per stdin)
Fixes: #379
> Fix broken pipe error on xenial integration tests

- pylxd/tests/mock_lxd.py
Signed-off-by: Lee Trager <lee.trager@canonical.com>
> Fix PEP8 errors introduced by new version.

- setup.cfg
This bumps the release number to 2.2.12 so that development
can continue.  Note the next release doesn't actually need to be 2.2.12.
> Bump release number for next cycle

- integration/test_networks.py
LXD now generates a stable MAC address for networks.
This is placed in volatile.bridge.hwaddr unless the network has a
pre-configured address.
This makes the current network test fail as it assumes that the config
returned after creation will be identical to that provided during
creation.
There are two ways of fixing this:
- Strip all volatile keys
- Provide a pre-set bridge.hwaddr key
This implements the latter.
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>
> test_networks: Avoid triggering volatile.bridge.hwaddr

- .git-blame-ignore-revs
This will allow git to ignore the reformatting changes, so `git blame`
keeps the original author.
> Add a .git-blame-ignore-revs

- .gitreview
- README.rst
This also drops the unused gerrit conf and removed dependency between lint and test jobs
> fix CI badge

- integration/run-integration-tests
- integration/test_client.py
- pylxd/client.py
- pylxd/tests/test_client.py
- tox.ini
This allows passing the project name as a string to Client and have it
automatically added to all URLs.
Blackened by @d0ugal for easier merging.
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>
Signed-off-by: Dougal Matthews <dougal@dougalmatthews.com>
> client: Add basic support for projects

- integration/test_projects.py
I think we can be confident that Pythons dict implementation is correct.
> Correct a typo in the integration test

- tox.ini
Drive-by clean up lint exclude.
> Remove broken/defunct pypy from tox.ini

- .github/workflows/ci.yml
- pylxd/deprecated/tests/test_certificate.py
- pylxd/deprecated/tests/test_connection.py
- pylxd/deprecated/tests/test_container.py
- pylxd/deprecated/tests/test_host.py
- pylxd/deprecated/tests/test_image.py
- pylxd/deprecated/tests/test_image_alias.py
- pylxd/deprecated/tests/test_network.py
- pylxd/deprecated/tests/test_operation.py
- pylxd/deprecated/tests/test_profiles.py
- pylxd/tests/models/test_instance.py
- pylxd/tests/models/test_network.py
- pylxd/tests/models/test_operation.py
- pylxd/tests/models/test_storage.py
- pylxd/tests/test_client.py
- setup.cfg
- tox.ini
The plan is to start adding type checks and verify them via mypy.
Also cleanup a bunch of mocck imports to import via unittest module.
> add tox target to typecheck via mypy

- pylxd/deprecated/connection.py
- pylxd/models/instance.py
https://mypy-lang.blogspot.com/2021/01/mypy-0800-released.html
MyPy 0.800 includes a check for the variable name of `namedtuple` to match the given name.
> Fix names of namedtuples to match variable names

- setup.cfg
Drive-by unify syntax in setup.cfg for check.
> Bump version to 2.3.1a

- pylxd/models/operation.py
This commit aims to fix a warning when using the operation model api on a
recent LXD version.
https://github.com/lxc/lxd/commit/55fcda838f549203d4cd52d19eb9166b0ed31945
introduced the `location` field to the operations model.
Signed-off-by: David Negreira <david.negreira@canonical.com>
> Add location to operation model

- .github/workflows/ci.yml
- doc/source/contributing.rst
- pylxd/client.py
- pylxd/deprecated/connection.py
- pylxd/models/instance.py
- pylxd/tests/models/test_instance.py
- pylxd/tests/test_client.py
- pylxd/tests/testing.py
- setup.cfg
ws4py is a required dependency, no need to check for it
This also splits the `coverage` and `py` tox targets so that's possible to use the latter to run a subset of tests
> cleanup ws4py and tox setup

- doc/source/instances.rst
Without the , it is not valid python code
> Adding missing , to example code

- pylxd/client.py
- pylxd/tests/test_client.py
This change allows to use the `events()` on remote clients, by passing the SSL certificate and keyfile from the HTTP client to to the websocket client.
I had to move the definition of `self.cert` to pick up the default certificates.
This fixes issue #381.
> Make the websocket client reuse the client's certificate

- pylxd/models/certificate.py
This silences warning about unknown attributes:
```
>>> import pylxd
>>> client = pylxd.Client()
>>> c = client.certificates.get('502cdfa1d3e2')
/usr/local/lib/python3.8/dist-packages/pylxd/models/_model.py:146: UserWarning: Attempted to set unknown attribute "restricted" on instance of "Certificate"
warnings.warn(
/usr/local/lib/python3.8/dist-packages/pylxd/models/_model.py:146: UserWarning: Attempted to set unknown attribute "projects" on instance of "Certificate"
warnings.warn(
>>> 
```
> Add projects and restricted attributes to certificates

- setup.cfg
> bump version to 2.3.2a

- integration/test_cluster_members.py
For some reason the PyLXD tests were expecting LXD to return valid
responses on the cluster API for standalone systems.
As LXD has now fixed this issue and is correctly returning the "Not clustered"
error for all those endpoints, the tests are now breaking.
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>
> integration: Skip cluster test when standalone

- doc/source/authentication.rst
- doc/source/usage.rst
Document how TLS fingerprint verification should be used, inspired by https://discuss.linuxcontainers.org/t/pylxd-certificate-verify-failed-self-signed-certificate/13232
While at it, simplify the self-signed client cert generation example to be easily copy-n-pasted.
> Improve TLS doc

- CONTRIBUTORS.rst
- doc/source/authentication.rst
- pylxd/client.py
- pylxd/models/instance.py
- pylxd/models/storage_pool.py
- setup.cfg
I ran `tox -e doc` and fixed all warnings and issues i found.
> Cleanup docs build

- .github/workflows/ci.yml
Signed-off-by: fliiiix <hi@l33t.name>
Because of this issue [here](https://github.com/lxc/pylxd/issues/500) i thought it would be nice it the github action keeps the tags and github release in sync. 
(A bit hard to test but i used it like this in other repos)
> github-action: auto create release on tag

- doc/source/usage.rst
- integration/run-integration-tests
- integration/test_client.py
- integration/test_projects.py
- pylxd/client.py
- pylxd/tests/test_client.py
Most notable changes:
* use proper path to TLS client certificate/key when using the snap
* opportunistic TLS server verification attempted by looking around for a server cert with a matching name
> Misc fixes

- pylxd/models/certificate.py
- pylxd/models/tests/test_certificate.py
Implemented to eventually address canonical/charm-lxd/issues/65 using PyLXD
> Add create_token method to get a token usable with lxc remote add

- pylxd/models/cluster.py
@stgraber the `config` and `groups` attributes are depending on recent API extensions, dunno if that requires special care here or not?
> Cluster fixes

- pylxd/managers.py
- pylxd/models/__init__.py
- pylxd/models/network.py
- pylxd/models/tests/test_network.py
- pylxd/tests/mock_lxd.py
Adding support for listing, creating, updating networks forwards as a child of networks.
Related issue https://github.com/lxc/pylxd/issues/520
> Adding support for network forwards

- .github/workflows/ci.yml
lets try again :upside_down_face:
> Fix: Github CI file os needs to be a array

- pylxd/models/instance.py
Closes #523 
LXD considers the socket in non-interactive mode as a pipe, much more than a Web socket. Indeed, once the command is finished executing, LXD "unpolitely" [closes the sockets](https://github.com/lxc/lxd/blob/master/lxd/instance_exec.go#L153) on its side without having the normal conversational close expected for Web Sockets ([see 5.5.1](https://www.rfc-editor.org/rfc/rfc6455#page-36)).
As the `pylxd` client was not informed, it tries to `recv` on a closed socket, hence raising a `ConnectionResetError`. It is arguable who is at fault here, whether the implementation done on `LXD`'s side is invalid, or if the `ws4py` isn't defensive enough with a Web socket being treated as a pipe and not a bi-directional stream by the counterpart.
This merge request suppresses the exception …
> bugfix: ConnectionResetError on container.execute

- setup.cfg
Black is pinned at `20.8b1` which is incompatible with `click` >= 8.1.0 (see https://stackoverflow.com/q/71673404 )
Bumping Black to something more recent is desirable, but will lead to a big diff. Until that can land, let's just pin click to be before the breaking version.
> Pin click at < 8.1.0 to avoid conflict with black

- .github/workflows/ci.yml
- pylxd/deprecated/connection.py
- pylxd/deprecated/image.py
- pylxd/deprecated/tests/test_image.py
- pylxd/managers.py
- pylxd/models/instance.py
- setup.cfg
Upgrade black version to 23.1.0
Bump Ubuntu version to 22.04 from 20.04 to run with Python 3.8
> Bump black to 23.1.0

- pylxd/client.py
- pylxd/tests/test_client.py
Fixes #360
Allow callers to modify the session and have it persisted through the API path traversal.
> Pass _APINode.session down to children classes

- pylxd/models/tests/test_instance.py
- pylxd/tests/test_client.py
Uncomment docstring for test_create_with_snap_lxd
> Clean up test_instance - remove defunct code

- CONTRIBUTORS.rst
- pylxd/client.py
- pylxd/tests/test_client.py
This (really) allows callers to customise the session before it's used.
Follow-on from #533. Fixes #360
> Extract get_session_for_url from Client.__init__

- doc/source/instances.rst
Nothing in the docs currently shows how pylxd can specify the target node on creation. The location can be read from the instance and is listed as an attribute, but specifying 'location' in the config on creation does not create the desired result.
> Add target node documentation

- setup.cfg
Otherwise with `urllib3` `2.0.2`:
```
>>> import pylxd
>>> c = pylxd.Client()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/var/lib/juju/agents/unit-lxd-6/charm/venv/pylxd/client.py", line 413, in __init__
response = self.api.get()
File "/var/lib/juju/agents/unit-lxd-6/charm/venv/pylxd/client.py", line 209, in get
response = self.session.get(self._api_endpoint, *args, **kwargs)
File "/var/lib/juju/agents/unit-lxd-6/charm/venv/requests/sessions.py", line 600, in get
return self.request("GET", url, **kwargs)
File "/var/lib/juju/agents/unit-lxd-6/charm/venv/requests/sessions.py", line 587, in request
resp = self.send(prep, **send_kwargs)
File "/var/lib/juju/agents/unit-lxd-6/charm/venv/requests/sessions.py", line 701, in send
r = adapter.send(request, …
```
> Pin `urllib3` to 1.x

- pylxd/models/instance.py
Resolves #548.
I have a project that I am working on that needs to support multi threading. Having pylxd make multiple http calls unfortunately makes my project a lot more complicated due to this. Instead of making something hacky in my project I decided to implement this to help my project and also implement more of the core LXD api.
Current implementation of `instances.all()`
```python
>>> for instance in client.instances.all():
...   print(instance.profiles)
... 
DEBUG:urllib3.connectionpool:https://dgreeley-test.mydomain.com:8443 "GET /1.0/instances?recursion=0 HTTP/1.1" 200 991
DEBUG:urllib3.connectionpool:https://dgreeley-test.mydomain.com:8443 "GET /1.0/instances/exampleinstance1 HTTP/1.1" 200 1910
['default']
DEBUG:urllib3.connectionpool:https://dgreeley-test.mydomain.com:8443 …
```
> instance(all): added passing recursion to all method to get all information in instance

- doc/source/instances.rst
- integration/test_storage.py
- pylxd/models/instance.py
This ended up fixing a small testing regression silently introduced by another PR.
>  pylxd/models/instance: only pass recursion if not 0
>  
>  This fixes `tox -e coverage`. This was not caught when introduced by
>  PR #551 because we our CI job was still only triggering on the old
>  branch name. The CI job was fixed afterward by commit 094bab4090776468.
>     
>  The decision to omit the recursion param was taken because that's easier
>  than trying to fix the mocked HTTP responses.
> Update code for fixed issues in LXD 

- .github/workflows/ci.yml
- .github/workflows/commits.yml
- .github/workflows/tests.yml
- doc/source/contributing.rst
- integration/run-integration-tests
- pylxd/client.py
- setup.cfg
A bunch of other fixes are also bundled in this PR but the biggest change is the integration tests being run on push/PR.
> github: Run integration tests

- integration/run-integration-tests
- integration/run-integration-tests-in-lxd
Also fix the main integration script to work with old LXD <5.
> Fix script to run integration tests in LXD

- .github/workflows/tests.yml
- pylxd/models/_model.py
- pylxd/models/operation.py
- setup.cfg
```
$ python3 -m twine check --strict dist/*
Checking dist/pylxd-2.3.2-py3-none-any.whl: PASSED
Checking dist/pylxd-2.3.2.tar.gz: PASSED
```
> Prepare `2.3.2` release

- integration/run-integration-tests-in-lxd
This reverts commit 06ab061297c89222e6ba8ca114f0c264ee3cc0ec now that `cloud-init` package in `ubuntu-daily:noble` is updated to the fixed version closing https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/2055219
> Revert "run-integration-tests-in-lxd: ignore error returned by cloud-init status

- setup.cfg
requests 2.32 security fix recommends a fix:
https://github.com/psf/requests/pull/6710
This was proposed (but not yet merged) to requests-unixsocket in:
https://github.com/msabramo/requests-unixsocket/pull/72
Fixes #579.
> setup.cfg: requests 2.32.0+ breaks requests-unixsocket

- integration/run-integration-tests
- integration/test_client.py
We don't have tests for token auth yet but that should be done as part of #589.
> Skip password auth tests if not supported by LXD

- doc/source/storage-pools.rst
- integration/test_storage.py
- integration/testing.py
- pylxd/managers.py
- pylxd/models/__init__.py
- pylxd/models/_model.py
- pylxd/models/storage_pool.py
This add a few features related to custom storage volumes snapshots to pyLXD:
1. Custom volume snapshot creation
2. Custom volume edition (including renaming)
4. Restoring a custom volume from a snapshot
5. Custom volume snapshot deletion
The unit tests will be added in a later PR if necessary.
Scheduling was already supported since it is done through config key settings on the StorageVolume object.
This also does some refactoring on previously existing code and some other changes made necessary by the new features and tests.
> Introduce storage volume snapshots

- .github/workflows/tests.yml
Fixes #586, probably due to `sudo -g lxd` not preserving the `$PATH` in which
the actions/setup-python had put the python executable.
> github: use canonical/setup-lxd action to setup LXD

- .github/workflows/tests.yml
#592 is a prerequisite
This PR is expected to fail until #590 is addressed.
> Test against `4.0/edge` on `22.04`

- integration/test_storage.py
- pylxd/models/storage_pool.py
Fixes #590.
Unfortunately, the best possible solution for `create` is picking the latest snapshot name when getting the object after creation.
This is prone to error if multiple snapshots of the same volume are being taken concurrently. But since this isn't a realistic use case, these changes should be acceptable in favor of not hurting UX by returning an empty object.
> Fix test regression on LXD 4.0

- README.rst
- doc/source/clustering.rst
- doc/source/storage-pools.rst
Older Python version didn't care but BCP is to use a venv and Python 3.12 actually requires it.
Fixes #596
> README: create a venv to pip install pylxd

- contrib_testing/local-http-test.py
- contrib_testing/local-unix-test.py
- contrib_testing/remote-test.py
- doc/source/authentication.rst
- doc/source/certificates.rst
- integration/run-integration-tests
- integration/test_client.py
- migration/run_migration_integration_tests-18-04
- migration/test_containers.py
- pylxd/client.py
- pylxd/models/certificate.py
- pylxd/tests/test_client.py
- setup.cfg
This updates the certificate creation to include the `trust_token` field and both the integration and migration tests. This does not update the LXD mock/unit tests and neither the broken integration tests.
> Add support for trust tokens

- pylxd/client.py
- pylxd/models/certificate.py
Fixes https://github.com/canonical/charm-lxd/issues/168 where charm-lxd is calling certificates.create():
```python
config: Dict[str, Union[str, bytes, List[str], bool]] = {
"name": name,
"password": "",
"cert_data": cert.encode(),
}
client.certificates.create(**config)
```
causing:
```
File "./src/charm.py", line 1139, in _on_https_relation_changed
if self.lxd_trust_add(cert=cert, name=cert_name, projects=projects):
File "./src/charm.py", line 2294, in lxd_trust_add
client.certificates.create(**config)
TypeError: create() got an unexpected keyword argument 'password'
```
This should fix an unexpected regression introduced in commit ec1b3ee10400bf2724e7818940a6320fe2319952.
> pylxd/models/certificate: re-add password arg for backward compat

- .gitignore
- pylxd/client.py
- pylxd/tests/test_client.py
- setup.cfg
This includes implementation to connect to a Unix socket without `requests_unixsocket`. This allows us to remove this dependency along with the version restrictions for `urllib3` and `requests`;
Fixes https://github.com/canonical/pylxd/issues/583 https://github.com/canonical/pylxd/issues/600
> Remove `requests_unixsocket`

- setup.cfg
Procedure:
```
$ python3 setup.py sdist
...
$ python3 setup.py bdist_wheel
...
$ python3 -m twine check --strict dist/*
Checking dist/pylxd-2.3.5-py3-none-any.whl: PASSED
Checking dist/pylxd-2.3.5.tar.gz: PASSED
$ python3 -m twine upload --repository pylxd-testpypi dist/*
Uploading distributions to https://test.pypi.org/legacy/
Uploading pylxd-2.3.5-py3-none-any.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.5/105.5 kB • 00:00 • 188.8 MB/s
Uploading pylxd-2.3.5.tar.gz
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.1/79.1 kB • 00:00 • 189.9 MB/s
View at:
https://test.pypi.org/project/pylxd/2.3.5/
```
The test upload is available at https://test.pypi.org/project/pylxd/2.3.5/
> setup.cfg: bump version to 2.3.5

- doc/source/authentication.rst
- doc/source/usage.rst
- pylxd/client.py
```
>>> import pylxd
>>> c = pylxd.Client(endpoint="https://127.0.0.1:8443/", cert=None,  verify=False)
/opt/pylxd/.tox/integration/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
warnings.warn(
>>> c.authenticate("password")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/opt/pylxd/.tox/integration/lib/python3.12/site-packages/pylxd/client.py", line 573, in authenticate
cert = open(self.api.session.cert[0]).read().encode("utf-8")
~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```
> pylxd/client: guard against cert=None

- pylxd/models/image.py
- pylxd/models/storage_pool.py
The integration tests are showing many warnings similar to `UserWarning: Attempted to set unknown attribute "type" on instance of "Image"`, due to PyLXD not recognizing some newish fields from a few API responses. This introduces such fields to PyLXD.
> Introduce missing fields on `StorageVolume` and `Image`

- doc/source/images.rst
- integration/test_images.py
- pylxd/models/image.py
- pylxd/models/tests/test_image.py
This removes a useless parameter that was supposed to be removed on 2.3 release.
> Drop `wait` argument from image create

- pylxd/client.py
- pylxd/models/instance.py
- pylxd/models/tests/test_instance.py
Fixes: https://github.com/canonical/pylxd/issues/666
> Make websockets use client's certificate data in `execute` method
