pylxd/hosts.py, pylxd/image.py
Changes the old print to the new print compatible with py2 and py3 and changes the error messages to reflect the actual error.
Doing the PR here because the steps given on the contributing.md are wrong.
Also not sure why this lib is under openstack?
=> proper print compatible with py2 and py3 and proper error messages

pylxd/api.py, pylxd/container.py
Signed-off-by: Matthew Williams <mgwilliams@gmail.com>
=> Add exec support.

pylxd/connection.py, pylxd/container.py
=> Fix os.enviorn -> os.environ

pylxd/api.py, pylxd/container.py, pylxd/tests/fake_api.py, pylxd/tests/test_container.py
Implement container file upload and related test.
=> Implement container file upload

pylxd/api.py, pylxd/connection.py, pylxd/container.py, pylxd/image.py, pylxd/operation.py, pylxd/tests/fake_api.py, pylxd/tests/test_container.py, pylxd/tests/test_image.py, requirements.txt
=> Add missing dependency to requirements.txt on eventlet, fixup py3 syntax

README.md, README.rst
Update the frontpage, add travis status (needs travis-ci to be enabled)
=> Travis status

pylxd/container.py, pylxd/tests/fake_api.py
LXD does not appear to be passing this back.
=> Drop use of criu key in metadata

setup.cfg
=> Bump to 0.18.

pylxd/connection.py
All requests were basically doing the same things, so it made sense
to unify those things into a single method, and create a better
experience around working with the response from that request.
The unit tests mock out most of this interaction, so it's hard to
verify, via unit tests, that this working properly, but I do have a
small and sloppy set of integration tests (that need to be...integrated)
that seem to indicate all is well (I was able to create, read, and
delete containers).
=> Refactor LXDConnection http requests.

setup.cfg
=> Bump to v0.19

requirements.txt, setup.py
This breaks devstack currently.
=> Update requests to not conflict.

pylxd/connection.py, pylxd/tests/test_connection.py
Closes #52
Signed-off-by: Sergio Schvezov <sergio.schvezov@canonical.com>
=> Support python 3.4+

setup.cfg
Bump version of pylxd to start matching lxd
=> Bump version 2.0.0b

pylxd/container.py, pylxd/containerState.py, setup.cfg
exemple: container.state().network['eth0']
=> Add state function on container to return state with network. 

pylxd/deprecated/api.py, pylxd/deprecated/container.py, pylxd/deprecated/hosts.py, pylxd/deprecated/tests/test_container.py
Fix container migration for recent versions of LXD.
=> Fix container migration

pylxd/deprecated/api.py, pylxd/deprecated/hosts.py
Add ability to query the host config.
=> Add host config API call

pylxd/container.py
=> Container methods fixed for freeze, unfreeze and restart

README.rst
There was no place in the repo that states how to install from PyPi or any other place. I thought this might be helpful.
=> Update README to display instructions of installing

examples/api_test.py, pylxd/container.py, pylxd/tests/mock_lxd.py
Update the example code. While doing this, I discovered a couple of issues with the code, and so I updated them, along with the tests.
=> New example

.travis.yml, tox.ini
This eliminates duplicate commands that were both in .travis.yml and tox.ini. Also, we can run the complete suite with the `tox` command now.
This prevents a coding style mistake from failing a python test job. Also prevents double execution of style checks.
=> Travis.yml update

doc/source/conf.py, doc/source/usage.rst, pylxd/client.py
It looks beautiful now, it's going to be so helpful when it's hosted online !
There's still a bit of work, but I'd like to get that merged for now because it's updating docstrings as well and rebasing is a bit of a pain, so please review and let me know if there's anything that needs to change here before we can merge this.
=> Update usage documentation

.travis.yml
=> Add codecov.io integration

integration/test_containers.py, integration/test_images.py, integration/testing.py, pylxd/client.py, pylxd/container.py, pylxd/exceptions.py, pylxd/image.py, pylxd/profile.py, pylxd/tests/mock_lxd.py, pylxd/tests/test_client.py, pylxd/tests/test_container.py, pylxd/tests/test_image.py, pylxd/tests/test_profile.py
Please review #129 first (this branch is based on that one; only the last two commits are relevant here)
This branch adds image export support, fixing issue #127
=> Image export

pylxd/client.py, pylxd/container.py, pylxd/exceptions.py, pylxd/image.py, pylxd/model.py, pylxd/profile.py, pylxd/tests/test_container.py, pylxd/tests/test_image.py, pylxd/tests/test_profile.py
- Remove the extra exceptions that aren't really needed with the introduction of `LXDAPIException`.
- Fix the assertions of responses for POST, to support LXD 2.0.3
=> Extraneous exceptions

setup.cfg
=> Bump version to 2.0.4

pylxd/container.py, pylxd/exceptions.py, pylxd/operation.py, pylxd/tests/test_container.py, pylxd/tests/test_operation.py
Snapshot publish is broken in LXD, but this is a guess for how
it is supposed to work, based on how it works in container
publish.
=> Add support for container and snapshot publish.

doc/source/images.rst, pylxd/image.py, pylxd/tests/mock_lxd.py, pylxd/tests/test_image.py
As discussed in the IRC with @rockstar here comes the IAS - Image Alias Support.
=> Add image aliases support.

doc/source/images.rst, pylxd/image.py, pylxd/tests/mock_lxd.py, pylxd/tests/test_image.py
This is a wip but @rockstar please review and give your thoughts.
=> Add images.copy()

pylxd/image.py, pylxd/model.py
=> Add Attribute.optional, this fixes auto_update with images.linuxcontainers.org

doc/source/images.rst, pylxd/image.py, pylxd/tests/mock_lxd.py, pylxd/tests/test_image.py
=> Add image.create_from_simplestreams and image.create_from_url.

integration/test_containers.py, integration/test_images.py, integration/test_profiles.py, pylxd/models/_model.py, pylxd/models/container.py
The integration tests were broken. While fixing them, I also changed `Model.__dirty__` to be a set, not a list.
=> Fix integration tests

pylxd/models/container.py
This means that this data can be re-used in cases where the client
is a unix socket. The API consumer can then massage the data
accordingly.
=> Extract the migration data step of migration.

test-requirements.txt
=> Remove the need for a mock-services branch

integration/test_containers.py, pylxd/models/container.py, pylxd/tests/models/test_container.py
2.2 will be out soon. This removes the single deprecation we had for 2.2
=> Remove code deprecated for 2.2

pylxd/models/_model.py, pylxd/models/container.py, pylxd/models/image.py
=> Change Operation calls to use the manager methods on client

CONTRIBUTORS.rst, setup.cfg
The email was originally for Paul Hummer.  I've changed that to the lxc-devel list and added a CONTRIBUTORS.rst to list the people who've contributed to the library.
=> Change the email address and add CONTRIBUTORS.rst

CONTRIBUTORS.rst, pylxd/client.py, pylxd/managers.py, pylxd/models/__init__.py, pylxd/models/storage_pool.py, pylxd/tests/mock_lxd.py, pylxd/tests/models/test_storage.py, setup.cfg
This adds basic support for storage pools as well
as tests to verify their function, taken from the
LXD REST API.
=> Add support for LXD storage pools

pylxd/client.py
This adds support for LXD being installed via snap
in addition to the traditional apt package.
Fixes #248
=> Update pylxd to look in snap path as well

pylxd/models/container.py
It would be nice to have this information.
=> include created_at for snapshot

pylxd/models/storage_pool.py, pylxd/tests/mock_lxd.py, pylxd/tests/models/test_storage.py
`exist()` and `create()` methods have been added for StoragePool class.
Appropriate tests have been added too.
=> Add storage pool methods

doc/source/profiles.rst, pylxd/models/profile.py, pylxd/tests/mock_lxd.py
Hi, 
I fix typos in profiles.rst when reading the documentation.
After that, I add "used_by" to profile attributes and arrange attributes in alphabetical order .
=> Add used_by to profile attributes

doc/source/containers.rst
Add examples for the items I just learned about, how to specify a profile, an image source, and find out what IP address a machine is using.
=> Add more examples

pylxd/client.py, pylxd/tests/test_client.py
The fix for storage pools in the __getattr__() in _APINode has
affected the names of containers and snapshots, if '_' are used in
the name.  This reverts most of that fix, adds tests, and special cases
'storage_pools' -> 'storage-pools' as an attribute ONLY, and not as
a name of a item.
Fixes: #295
=> Remove overzealous '_' -> '-' subsitution in _APINode

setup.cfg
Also, drop Python 3.3 and add Python 3.6 to the target Python
versions in setup.cfg
=> Bump version to 2.2.8 for next round of development

README.rst, doc/source/contributing.rst
Add more to the contributing guide about testing, integration testing,
pep8, and signing off commits.  These are frequent questions/issues.
=> Add more information about contributing to pyLXD

doc/source/contributing.rst
=> Fix some typos in recent change.

setup.cfg
=> Update version to 2.2.11 for next dev cycle

integration/test_containers.py, pylxd/models/container.py, pylxd/tests/models/test_container.py
=> option to not store command stdout/stderr

.coveragerc, CONTRIBUTORS.rst
Signed-off-by: Anne Borcherding <anne.borcherding@iosb.fraunhofer.de>
=> Added setting to show missing lines of test coverage

integration/test_networks.py
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>
=> test_networks: Make hwaddr conditional on extension

doc/source/images.rst
This solves issue #405 as I ran into the same problem and assumed that I need to implement the delete myself.
Signed-off-by: Felix Engelmann <fe-github@nlogn.org>
=> Documentation for Image deletion

pylxd/models/cluster.py
Signed-off-by: Dougal Matthews <dougal@dougalmatthews.com>
=> Remove debugging prints

.github/workflows/ci.yml, README.rst
=> don't depend CI jobs

.git-blame-ignore-revs, contrib_testing/local-http-test.py, contrib_testing/local-unix-test.py, contrib_testing/remote-test.py, integration/busybox.py, integration/test_client.py, integration/test_cluster_members.py, integration/test_containers.py, integration/test_images.py, integration/test_networks.py, integration/test_profiles.py, integration/test_storage.py, integration/testing.py, migration/busybox.py, migration/test_containers.py, migration/testing.py, tox.ini
Signed-off-by: Dougal Matthews <dougal@dougalmatthews.com>
=> Blacken and isort contrib_testing, integration and migration code

setup.cfg
=> Update version to 2.3.0a1

.gitignore, .mailmap, MANIFEST.in
=> fix manifest, cleanup .gitignore

integration/test_projects.py, integration/testing.py, pylxd/client.py, pylxd/managers.py, pylxd/models/__init__.py, pylxd/models/project.py, pylxd/tests/mock_lxd.py, pylxd/tests/models/test_project.py
Signed-off-by: Dougal Matthews <dougal@dougalmatthews.com>
=> Add support for lxd projects

pylxd/client.py, pylxd/tests/test_client.py
=> fix project support detection when project is provided

pylxd/tests/test_client.py
=> Change mock responses to be a single list of mocked response values

doc/source/api.rst, doc/source/index.rst, doc/source/projects.rst
=> Add documentation for projects.

doc/source/api.rst, doc/source/networks.rst, pylxd/models/container.py, pylxd/models/virtual_machine.py
Add Instance and VirtualMachine docs. Clear up Network docs.
=> Docs cleanup

test-requirements.txt
=> drop unused test-requirements.txt

setup.cfg
=> Add doc target to setup.cfg

setup.cfg
=> drop unused i18n sections

setup.cfg
=> Release 2.3.0

pylxd/client.py, pylxd/deprecated/connection.py, pylxd/models/instance.py
=> replace namedtuple with NamedTuple

doc/source/installation.rst
=> Remove instructions about installing from APT.

pylxd/client.py, pylxd/tests/test_client.py
Signed-off-by: Dario Mohaddes <m.dariuz@gmail.com>
=> changed os.path.isfile() to os.path.exixsts in client.py

pylxd/models/instance.py, pylxd/tests/models/test_instance.py
=> Update Instance.execute exposing exec API options

setup.cfg
=> add typecheck stubs to make checks pass

integration/run-integration-tests-in-lxd
=> run-integration-tests-in-lxd-fix: commit missing fixes from previous change

.github/workflows/ci.yml, setup.cfg
=> Release 2.3.1

doc/source/clustering.rst, doc/source/storage-pools.rst, doc/source/usage.rst, pylxd/models/storage_pool.py
Document Client(project='...') and update links to LXD documentation while at it.
=> Project doc

doc/source/instances.rst
Stop referring to EOL images while at it.
=> doc/instances: improve doc around image use

pylxd/models/tests/test_network.py
=> Fixing linting issues

.github/workflows/commits.yml
We've renamed `master` to `main` so we need to also change this workflow job.
=> workflows: Changes target branch check to main.

pylxd/models/image.py
Adds support for VM type images.
=> feat: add vm img support

setup.cfg
Procedure:
```
$ python3 setup.py sdist
...
$ python3 setup.py bdist_wheel
...
$ python3 -m twine check --strict dist/*
Checking dist/pylxd-2.3.4-py3-none-any.whl: PASSED
Checking dist/pylxd-2.3.4.tar.gz: PASSED
$ python3 -m twine upload --repository pylxd-testpypi dist/*
Uploading distributions to https://test.pypi.org/legacy/
Uploading pylxd-2.3.4-py3-none-any.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.2/102.2 kB • 00:04 • 176.2 MB/s
Uploading pylxd-2.3.4.tar.gz
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB • 00:00 • 149.8 MB/s
View at:
https://test.pypi.org/project/pylxd/2.3.4/
```
The test upload is available at https://test.pypi.org/project/pylxd/2.3.4/
=> setup.cfg: bump version to 2.3.4

.github/workflows/codeql.yml, .github/workflows/tests.yml
=> Update GitHub actions
